defaults: &defaults
  GMAIL_USERNAME: mobilize.test1@gmail.com
  GMAIL_PASSWORD: Mobilize@1121026
  
production:
  <<: *defaults
  #HOST_URL: http://www.mobilizezone.com
  RAILS_SERVE_STATIC_FILES: true

development:
  <<: *defaults
  HOST_URL: http://localhost:3000