defaults: &defaults
  GMAIL_USERNAME: mobilize.test1@gmail.com
  GMAIL_PASSWORD: Mobilize@1121026
  
production:
  <<: *defaults
  HOST_URL: http://www.mobilizezone.com
  RDS_DB_NAME: ebdb
  RDS_USERNAME: sanojkiit
  RDS_PASSWORD: SanoJ26KiiT
  RDS_HOSTNAME: aa1rkib9nxnfx5z.cu6rlts9xz99.ap-south-1.rds.amazonaws.com:3306
  RDS_PORT: 3306

development:
  <<: *defaults
  HOST_URL: http://localhost:3000